#import <Foundation/Foundation.h>
#import "ACObject.h"

/**
* ARTIK Cloud API
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: 2.0.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "ACValidityPeriod.h"


@protocol ACCertificateFields
@end

@interface ACCertificateFields : ACObject

/* version [optional]
 */
@property(nonatomic) NSNumber* version;
/* serialNumber [optional]
 */
@property(nonatomic) NSString* serialNumber;
/* signatureAlgorithm [optional]
 */
@property(nonatomic) NSString* signatureAlgorithm;
/* subject [optional]
 */
@property(nonatomic) NSString* subject;
/* issuer [optional]
 */
@property(nonatomic) NSString* issuer;

@property(nonatomic) ACValidityPeriod* validity;

@end
