#import <Foundation/Foundation.h>
#import "ACObject.h"

/**
* ARTIK Cloud API
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: 2.0.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/




@protocol ACDeviceSharing
@end

@interface ACDeviceSharing : ACObject

/* Share ID [optional]
 */
@property(nonatomic) NSString* _id;
/* Email [optional]
 */
@property(nonatomic) NSString* email;
/* Status [optional]
 */
@property(nonatomic) NSString* status;
/* Shared on [optional]
 */
@property(nonatomic) NSNumber* sharedOn;

@end
