#import <Foundation/Foundation.h>
#import "ACObject.h"

/**
* ARTIK Cloud API
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: 2.0.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/




@protocol ACDeviceRegConfirmUserRequest
@end

@interface ACDeviceRegConfirmUserRequest : ACObject

/* Device ID. Optional if deviceName is present [optional]
 */
@property(nonatomic) NSString* deviceId;
/* Device Name. Optional if deviceId is present [optional]
 */
@property(nonatomic) NSString* deviceName;
/* Pin obtained in the registrations call. [optional]
 */
@property(nonatomic) NSString* pin;

@end
