#import <Foundation/Foundation.h>
#import "ACObject.h"

/**
* ARTIK Cloud API
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: 2.0.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "ACContactInfo.h"
#import "ACTier.h"


@protocol ACDeviceTypePricingTier
@end

@interface ACDeviceTypePricingTier : ACObject

/* revenue share percentage [optional]
 */
@property(nonatomic) NSObject* revenueSharePercent;
/* tiers [optional]
 */
@property(nonatomic) NSArray<ACTier>* tiers;
/* modified on [optional]
 */
@property(nonatomic) NSNumber* modifiedOn;
/* comments [optional]
 */
@property(nonatomic) NSString* comments;
/* dtid [optional]
 */
@property(nonatomic) NSString* dtid;
/* contact information [optional]
 */
@property(nonatomic) ACContactInfo* contactInfo;
/* type [optional]
 */
@property(nonatomic) NSString* ptType;
/* version [optional]
 */
@property(nonatomic) NSNumber* version;
/* created on [optional]
 */
@property(nonatomic) NSNumber* createdOn;
/* status [optional]
 */
@property(nonatomic) NSString* status;

@end
