#import <Foundation/Foundation.h>
#import "ACObject.h"

/**
* ARTIK Cloud API
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: 2.0.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/




@protocol ACDeviceTypesInfo
@end

@interface ACDeviceTypesInfo : ACObject

/* Device Properties Enabled [optional]
 */
@property(nonatomic) NSNumber* devicePropertiesEnabled;
/* Pmax value [optional]
 */
@property(nonatomic) NSNumber* pmax;
/* Modified on [optional]
 */
@property(nonatomic) NSNumber* modifiedOn;
/* Device Type ID [optional]
 */
@property(nonatomic) NSString* dtid;
/* Pmin value [optional]
 */
@property(nonatomic) NSNumber* pmin;
/* Default task expiration time in seconds [optional]
 */
@property(nonatomic) NSNumber* taskExpiresAfter;
/* Created on [optional]
 */
@property(nonatomic) NSNumber* createdOn;

@end
