#import <Foundation/Foundation.h>
#import "ACObject.h"

/**
* ARTIK Cloud API
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: 2.0.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/




@protocol ACEventFeedData
@end

@interface ACEventFeedData : ACObject

/* Event [optional]
 */
@property(nonatomic) NSString* event;
/* Timestamp [optional]
 */
@property(nonatomic) NSNumber* ts;
/* Message Payload [optional]
 */
@property(nonatomic) NSDictionary<NSString*, NSObject*>* data;

@end
