#import <Foundation/Foundation.h>
#import "ACObject.h"

/**
* ARTIK Cloud API
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: 2.0.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/




@protocol ACExportRequest
@end

@interface ACExportRequest : ACObject


@property(nonatomic) NSNumber* endDate;

@property(nonatomic) NSString* format;

@property(nonatomic) NSString* order;

@property(nonatomic) NSString* sdids;

@property(nonatomic) NSString* sdtids;

@property(nonatomic) NSNumber* startDate;

@property(nonatomic) NSString* trialId;

@property(nonatomic) NSString* uids;

@end
