#import <Foundation/Foundation.h>
#import "ACObject.h"

/**
* ARTIK Cloud API
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: 2.0.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "ACExportRequest.h"


@protocol ACExportData
@end

@interface ACExportData : ACObject


@property(nonatomic) NSNumber* expirationDate;

@property(nonatomic) NSString* exportId;

@property(nonatomic) NSNumber* fileSize;

@property(nonatomic) NSString* md5;

@property(nonatomic) ACExportRequest* request;
/* Export status [optional]
 */
@property(nonatomic) NSString* status;

@property(nonatomic) NSNumber* totalMessages;

@end
