#import <Foundation/Foundation.h>
#import "ACObject.h"

/**
* ARTIK Cloud API
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: 2.0.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "ACFieldPresence.h"


@protocol ACFieldPresenceEnvelope
@end

@interface ACFieldPresenceEnvelope : ACObject


@property(nonatomic) NSString* sdid;

@property(nonatomic) NSString* fieldPresence;

@property(nonatomic) NSNumber* startDate;

@property(nonatomic) NSNumber* endDate;

@property(nonatomic) NSString* interval;

@property(nonatomic) NSNumber* size;

@property(nonatomic) NSArray<ACFieldPresence>* data;

@end
