#import <Foundation/Foundation.h>
#import "ACObject.h"

/**
* ARTIK Cloud API
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: 2.0.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/




@protocol ACMessageAction
@end

@interface ACMessageAction : ACObject


@property(nonatomic) NSDictionary<NSString*, NSObject*>* data;
/* Destination Device ID. [optional]
 */
@property(nonatomic) NSString* ddid;
/* Source Device ID. [optional]
 */
@property(nonatomic) NSString* sdid;
/* Timestamp (past, present or future). Defaults to current time if not provided. [optional]
 */
@property(nonatomic) NSNumber* ts;
/* Type. [optional]
 */
@property(nonatomic) NSString* type;

@end
