#import <Foundation/Foundation.h>
#import "ACObject.h"

/**
* ARTIK Cloud API
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: 2.0.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "ACCreateModelData.h"
#import "ACField.h"
#import "ACParameters.h"


@protocol ACModelResponseData
@end

@interface ACModelResponseData : ACObject


@property(nonatomic) NSArray<ACField>* outputs;

@property(nonatomic) NSString* uid;

@property(nonatomic) ACCreateModelData* data;

@property(nonatomic) NSString* trainingCron;

@property(nonatomic) NSArray<ACField>* inputs;

@property(nonatomic) NSString* origin;

@property(nonatomic) NSString* _id;

@property(nonatomic) NSString* type;

@property(nonatomic) ACParameters* parameters;

@property(nonatomic) NSNumber* version;

@property(nonatomic) NSString* aid;

@property(nonatomic) NSString* status;

@end
