#import <Foundation/Foundation.h>
#import "ACObject.h"

/**
* ARTIK Cloud API
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: 2.0.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "ACNotifMessageArray.h"


@protocol ACNotifMessagesResponse
@end

@interface ACNotifMessagesResponse : ACObject


@property(nonatomic) NSNumber* total;

@property(nonatomic) NSNumber* offset;

@property(nonatomic) ACNotifMessageArray* data;

@property(nonatomic) NSNumber* count;

@property(nonatomic) NSString* order;

@end
