#import <Foundation/Foundation.h>
#import "ACObject.h"

/**
* ARTIK Cloud API
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: 2.0.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "ACNormalizedAction.h"


@protocol ACNormalizedActionsEnvelope
@end

@interface ACNormalizedActionsEnvelope : ACObject


@property(nonatomic) NSString* ddids;

@property(nonatomic) NSString* ddid;

@property(nonatomic) NSString* uid;

@property(nonatomic) NSNumber* startDate;

@property(nonatomic) NSNumber* endDate;

@property(nonatomic) NSString* order;

@property(nonatomic) NSString* next;

@property(nonatomic) NSNumber* count;

@property(nonatomic) NSNumber* size;

@property(nonatomic) NSArray<ACNormalizedAction>* data;

@end
