#import <Foundation/Foundation.h>
#import "ACObject.h"

/**
* ARTIK Cloud API
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: 2.0.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/




@protocol ACOutputScene
@end

@interface ACOutputScene : ACObject


@property(nonatomic) NSString* _id;

@property(nonatomic) NSString* uid;

@property(nonatomic) NSString* aid;

@property(nonatomic) NSString* name;

@property(nonatomic) NSString* _description;

@property(nonatomic) NSDictionary<NSString*, NSObject*>* actions;

@property(nonatomic) NSDictionary<NSString*, NSObject*>* error;

@end
