#import <Foundation/Foundation.h>
#import "ACObject.h"

/**
* ARTIK Cloud API
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: 2.0.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "ACRejectedCSVRow.h"


@protocol ACRejectedCSVRowsEnvelope
@end

@interface ACRejectedCSVRowsEnvelope : ACObject

/* Page starting position [optional]
 */
@property(nonatomic) NSNumber* offset;
/* Page size [optional]
 */
@property(nonatomic) NSNumber* count;
/* Total number or rejected rows [optional]
 */
@property(nonatomic) NSNumber* total;
/* Array of rejected rows [optional]
 */
@property(nonatomic) NSArray<ACRejectedCSVRow>* data;

@end
