#import <Foundation/Foundation.h>
#import "ACObject.h"

/**
* ARTIK Cloud API
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: 2.0.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/




@protocol ACRuleCreationInfo
@end

@interface ACRuleCreationInfo : ACObject

/* Description [optional]
 */
@property(nonatomic) NSString* _description;
/* Is Enabled [optional]
 */
@property(nonatomic) NSNumber* enabled;
/* Name [optional]
 */
@property(nonatomic) NSString* name;
/* Rule [optional]
 */
@property(nonatomic) NSDictionary<NSString*, NSObject*>* rule;

@end
