#import <Foundation/Foundation.h>
#import "ACObject.h"

/**
* ARTIK Cloud API
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: 2.0.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "ACFieldPath.h"


@protocol ACRuleError
@end

@interface ACRuleError : ACObject


@property(nonatomic) NSNumber* errorCode;

@property(nonatomic) ACFieldPath* fieldPath;

@property(nonatomic) NSArray<NSString*>* messageArgs;

@property(nonatomic) NSString* messageKey;

@end
