#import <Foundation/Foundation.h>
#import "ACObject.h"

/**
* ARTIK Cloud API
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: 2.0.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/




@protocol ACSubscriptionInfo
@end

@interface ACSubscriptionInfo : ACObject

/* AWS region (if subscriptionType is awsKinesis [optional]
 */
@property(nonatomic) NSString* awsRegion;
/* Description [optional]
 */
@property(nonatomic) NSString* _description;
/* AWS key (if subscriptionType is awsKinesis [optional]
 */
@property(nonatomic) NSString* awsKey;
/* AWS secret (if subscriptionType is awsKinesis [optional]
 */
@property(nonatomic) NSString* awsSecret;
/* AWS Kinesis stream name (if subscriptionType is awsKinesis [optional]
 */
@property(nonatomic) NSString* awsKinesisStreamName;
/* User ID [optional]
 */
@property(nonatomic) NSString* uid;
/* Message type [optional]
 */
@property(nonatomic) NSString* messageType;
/* Destination device ID [optional]
 */
@property(nonatomic) NSString* ddid;
/* Subscription type (either httpCallback or awsKinesis, default to httpCallback) [optional]
 */
@property(nonatomic) NSString* subscriptionType;
/* Name [optional]
 */
@property(nonatomic) NSString* name;
/* Source device ID [optional]
 */
@property(nonatomic) NSString* sdid;
/* Callback URL [optional]
 */
@property(nonatomic) NSString* callbackUrl;
/* Source device type ID [optional]
 */
@property(nonatomic) NSString* sdtid;

@end
