#import <Foundation/Foundation.h>
#import "ACObject.h"

/**
* ARTIK Cloud API
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: 2.0.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/




@protocol ACTaskStatusCounts
@end

@interface ACTaskStatusCounts : ACObject

/* Number failed [optional]
 */
@property(nonatomic) NSNumber* numFailed;
/* Number cancelled [optional]
 */
@property(nonatomic) NSNumber* numCancelled;
/* Total devices [optional]
 */
@property(nonatomic) NSNumber* totalDevices;
/* Number completed [optional]
 */
@property(nonatomic) NSNumber* numCompleted;
/* Number succeeded [optional]
 */
@property(nonatomic) NSNumber* numSucceeded;

@end
