#import <Foundation/Foundation.h>
#import "ACObject.h"

/**
* ARTIK Cloud API
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: 2.0.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "ACTaskList.h"
#import "ACTasksStatusCounts.h"


@protocol ACTaskListEnvelope
@end

@interface ACTaskListEnvelope : ACObject

/* Total [optional]
 */
@property(nonatomic) NSNumber* total;
/* Envelope for task list [optional]
 */
@property(nonatomic) ACTaskList* data;
/* Status counts [optional]
 */
@property(nonatomic) ACTasksStatusCounts* statusCounts;
/* Offset [optional]
 */
@property(nonatomic) NSNumber* offset;
/* Count [optional]
 */
@property(nonatomic) NSNumber* count;

@end
