#import <Foundation/Foundation.h>
#import "ACObject.h"

/**
* ARTIK Cloud API
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: 2.0.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "ACUpdateParameters.h"


@protocol ACTaskParameters
@end

@interface ACTaskParameters : ACObject

/* Expire time in seconds [optional]
 */
@property(nonatomic) NSNumber* expiresAfter;
/* Future scheduled time [optional]
 */
@property(nonatomic) NSNumber* scheduledOn;
/* Update parameters [optional]
 */
@property(nonatomic) ACUpdateParameters* update;
/* Value to write [optional]
 */
@property(nonatomic) NSString* value;

@end
