#import <Foundation/Foundation.h>
#import "ACObject.h"

/**
* ARTIK Cloud API
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: 2.0.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/




@protocol ACTasksStatusCounts
@end

@interface ACTasksStatusCounts : ACObject

/* Cancelled [optional]
 */
@property(nonatomic) NSNumber* cANCELLED;
/* Complete [optional]
 */
@property(nonatomic) NSNumber* cOMPLETE;
/* Processing [optional]
 */
@property(nonatomic) NSNumber* pROCESSING;
/* Requested [optional]
 */
@property(nonatomic) NSNumber* rEQUESTED;

@end
