#import <Foundation/Foundation.h>
#import "ACObject.h"

/**
* ARTIK Cloud API
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: 2.0.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "ACTaskParameters.h"


@protocol ACTaskRequest
@end

@interface ACTaskRequest : ACObject

/* Filter [optional]
 */
@property(nonatomic) NSString* filter;
/* Task type [optional]
 */
@property(nonatomic) NSString* taskType;
/* Device Type ID [optional]
 */
@property(nonatomic) NSString* dtid;
/* Property [optional]
 */
@property(nonatomic) NSString* _property;
/* Device IDs [optional]
 */
@property(nonatomic) NSArray<NSString*>* dids;
/* Task parameters [optional]
 */
@property(nonatomic) ACTaskParameters* taskParameters;

@end
