#import <Foundation/Foundation.h>
#import "ACObject.h"

/**
* ARTIK Cloud API
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: 2.0.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/




@protocol ACTag
@end

@interface ACTag : ACObject

/* Tag Name. [optional]
 */
@property(nonatomic) NSString* name;
/* Is Category. [optional]
 */
@property(nonatomic) NSNumber* isCategory;

@end
