#import <Foundation/Foundation.h>
#import "ACObject.h"

/**
* ARTIK Cloud API
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: 2.0.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "ACTaskByDidList.h"


@protocol ACTaskByDidListEnvelope
@end

@interface ACTaskByDidListEnvelope : ACObject

/* Total number of tasks in list [optional]
 */
@property(nonatomic) NSNumber* total;
/* Device task list envelope [optional]
 */
@property(nonatomic) ACTaskByDidList* data;
/* Offset if using pagination [optional]
 */
@property(nonatomic) NSNumber* offset;
/* Count for current result set [optional]
 */
@property(nonatomic) NSNumber* count;

@end
