#import <Foundation/Foundation.h>
#import "ACObject.h"

/**
* ARTIK Cloud API
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: 2.0.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/




@protocol ACTier
@end

@interface ACTier : ACObject

/* Modified On [optional]
 */
@property(nonatomic) NSNumber* modifiedOn;
/* Message Limit [optional]
 */
@property(nonatomic) NSNumber* messageLimit;
/* Cost [optional]
 */
@property(nonatomic) NSString* cost;
/* Name [optional]
 */
@property(nonatomic) NSString* name;
/* Description [optional]
 */
@property(nonatomic) NSString* _description;
/* Interval [optional]
 */
@property(nonatomic) NSString* interval;
/* Pricing Tier ID [optional]
 */
@property(nonatomic) NSString* ptid;
/* Type [optional]
 */
@property(nonatomic) NSString* type;
/* Billing Interval [optional]
 */
@property(nonatomic) NSString* billingInterval;
/* Created On [optional]
 */
@property(nonatomic) NSNumber* createdOn;

@end
