#import <Foundation/Foundation.h>
#import "ACObject.h"

/**
* ARTIK Cloud API
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: 2.0.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/




@protocol ACTokenInfo
@end

@interface ACTokenInfo : ACObject


@property(nonatomic) NSString* clientId;

@property(nonatomic) NSString* deviceId;

@property(nonatomic) NSNumber* expiresIn;

@property(nonatomic) NSString* userId;

@end
