#import <Foundation/Foundation.h>
#import "ACObject.h"

/**
* ARTIK Cloud API
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: 2.0.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/




@protocol ACWebSocketError
@end

@interface ACWebSocketError : ACObject

/* Message. [optional]
 */
@property(nonatomic) NSString* message;
/* Code [optional]
 */
@property(nonatomic) NSNumber* code;
/* Confirmation ID [optional]
 */
@property(nonatomic) NSString* cid;

@end
