#import <Foundation/Foundation.h>
#import "ACObject.h"

/**
* ARTIK Cloud API
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: 2.0.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "ACWhitelist.h"


@protocol ACWhitelistResultEnvelope
@end

@interface ACWhitelistResultEnvelope : ACObject

/* Device type id [optional]
 */
@property(nonatomic) NSString* dtid;
/* Page starting position [optional]
 */
@property(nonatomic) NSNumber* offset;
/* Page size [optional]
 */
@property(nonatomic) NSNumber* count;
/* Total number or whitelist vdids [optional]
 */
@property(nonatomic) NSNumber* total;
/* Array of whitelisted vdids [optional]
 */
@property(nonatomic) NSArray<ACWhitelist>* data;

@end
