#import <Foundation/Foundation.h>
#import "ACScenesEnvelope.h"
#import "ACApi.h"

/**
* ARTIK Cloud API
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: 2.0.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/



@interface ACDefaultApi: NSObject <ACApi>

extern NSString* kACDefaultApiErrorDomain;
extern NSInteger kACDefaultApiMissingParamErrorCode;

-(instancetype) initWithApiClient:(ACApiClient *)apiClient NS_DESIGNATED_INITIALIZER;

/// Get all user scenes
/// Get all user scenes
///
/// @param uid User id
/// @param count count (optional)
/// @param offset offset (optional)
/// 
///  code:0 message:"success"
///
/// @return ACScenesEnvelope*
-(NSURLSessionTask*) getUserScenesWithUid: (NSString*) uid
    count: (NSString*) count
    offset: (NSString*) offset
    completionHandler: (void (^)(ACScenesEnvelope* output, NSError* error)) handler;



@end
