#import <Foundation/Foundation.h>
#import "ACDevice.h"
#import "ACDeviceEnvelope.h"
#import "ACDeviceTokenEnvelope.h"
#import "ACPresenceEnvelope.h"
#import "ACApi.h"

/**
* ARTIK Cloud API
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: 2.0.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/



@interface ACDevicesApi: NSObject <ACApi>

extern NSString* kACDevicesApiErrorDomain;
extern NSInteger kACDevicesApiMissingParamErrorCode;

-(instancetype) initWithApiClient:(ACApiClient *)apiClient NS_DESIGNATED_INITIALIZER;

/// Add Device
/// Create a device
///
/// @param device Device to be added to the user
/// 
///  code:0 message:"success"
///
/// @return ACDeviceEnvelope*
-(NSURLSessionTask*) addDeviceWithDevice: (ACDevice*) device
    completionHandler: (void (^)(ACDeviceEnvelope* output, NSError* error)) handler;


/// Delete Device
/// Deletes a device
///
/// @param deviceId deviceId
/// 
///  code:0 message:"success"
///
/// @return ACDeviceEnvelope*
-(NSURLSessionTask*) deleteDeviceWithDeviceId: (NSString*) deviceId
    completionHandler: (void (^)(ACDeviceEnvelope* output, NSError* error)) handler;


/// Delete Device Token
/// Deletes a device's token
///
/// @param deviceId deviceId
/// 
///  code:0 message:"success"
///
/// @return ACDeviceTokenEnvelope*
-(NSURLSessionTask*) deleteDeviceTokenWithDeviceId: (NSString*) deviceId
    completionHandler: (void (^)(ACDeviceTokenEnvelope* output, NSError* error)) handler;


/// Get Device
/// Retrieves a device
///
/// @param deviceId deviceId
/// 
///  code:0 message:"success"
///
/// @return ACDeviceEnvelope*
-(NSURLSessionTask*) getDeviceWithDeviceId: (NSString*) deviceId
    completionHandler: (void (^)(ACDeviceEnvelope* output, NSError* error)) handler;


/// Get device presence information
/// Return the presence status of the given device along with the time it was last seen
///
/// @param deviceId Device ID.
/// 
///  code:0 message:"success"
///
/// @return ACPresenceEnvelope*
-(NSURLSessionTask*) getDevicePresenceWithDeviceId: (NSString*) deviceId
    completionHandler: (void (^)(ACPresenceEnvelope* output, NSError* error)) handler;


/// Get Device Token
/// Retrieves a device's token
///
/// @param deviceId deviceId
/// 
///  code:0 message:"success"
///
/// @return ACDeviceTokenEnvelope*
-(NSURLSessionTask*) getDeviceTokenWithDeviceId: (NSString*) deviceId
    completionHandler: (void (^)(ACDeviceTokenEnvelope* output, NSError* error)) handler;


/// Update Device
/// Updates a device
///
/// @param deviceId deviceId
/// @param device Device to be updated
/// 
///  code:0 message:"success"
///
/// @return ACDeviceEnvelope*
-(NSURLSessionTask*) updateDeviceWithDeviceId: (NSString*) deviceId
    device: (ACDevice*) device
    completionHandler: (void (^)(ACDeviceEnvelope* output, NSError* error)) handler;


/// Update Device Token
/// Updates a device's token
///
/// @param deviceId deviceId
/// 
///  code:0 message:"success"
///
/// @return ACDeviceTokenEnvelope*
-(NSURLSessionTask*) updateDeviceTokenWithDeviceId: (NSString*) deviceId
    completionHandler: (void (^)(ACDeviceTokenEnvelope* output, NSError* error)) handler;



@end
