#import <Foundation/Foundation.h>
#import "ACDeviceStatus.h"
#import "ACDeviceStatusBatch.h"
#import "ACDeviceStatusPut.h"
#import "ACApi.h"

/**
* ARTIK Cloud API
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: 2.0.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/



@interface ACDevicestatusApi: NSObject <ACApi>

extern NSString* kACDevicestatusApiErrorDomain;
extern NSInteger kACDevicestatusApiMissingParamErrorCode;

-(instancetype) initWithApiClient:(ACApiClient *)apiClient NS_DESIGNATED_INITIALIZER;

/// Get Device Status
/// Get Device Status
///
/// @param deviceId Device ID.
/// @param includeSnapshot Include device snapshot into the response (optional)
/// @param includeSnapshotTimestamp Include device snapshot timestamp into the response (optional)
/// 
///  code:0 message:"success"
///
/// @return ACDeviceStatus*
-(NSURLSessionTask*) getDeviceStatusWithDeviceId: (NSString*) deviceId
    includeSnapshot: (NSNumber*) includeSnapshot
    includeSnapshotTimestamp: (NSNumber*) includeSnapshotTimestamp
    completionHandler: (void (^)(ACDeviceStatus* output, NSError* error)) handler;


/// Get Devices Status
/// Get Devices Status
///
/// @param dids List of device ids (comma-separated) for which the statuses are requested.
/// @param includeSnapshot Include device snapshot into the response (optional)
/// @param includeSnapshotTimestamp Include device snapshot timestamp into the response (optional)
/// 
///  code:0 message:"success"
///
/// @return ACDeviceStatusBatch*
-(NSURLSessionTask*) getDevicesStatusWithDids: (NSString*) dids
    includeSnapshot: (NSNumber*) includeSnapshot
    includeSnapshotTimestamp: (NSNumber*) includeSnapshotTimestamp
    completionHandler: (void (^)(ACDeviceStatusBatch* output, NSError* error)) handler;


/// Update Device Status
/// Update Device Status
///
/// @param deviceId Device ID.
/// @param body Body (optional)
/// 
///  code:0 message:"success"
///
/// @return ACDeviceStatus*
-(NSURLSessionTask*) putDeviceStatusWithDeviceId: (NSString*) deviceId
    body: (ACDeviceStatusPut*) body
    completionHandler: (void (^)(ACDeviceStatus* output, NSError* error)) handler;



@end
