#import <Foundation/Foundation.h>
#import "ACRuleCreationInfo.h"
#import "ACRuleEnvelope.h"
#import "ACRuleUpdateInfo.h"
#import "ACApi.h"

/**
* ARTIK Cloud API
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: 2.0.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/



@interface ACRulesApi: NSObject <ACApi>

extern NSString* kACRulesApiErrorDomain;
extern NSInteger kACRulesApiMissingParamErrorCode;

-(instancetype) initWithApiClient:(ACApiClient *)apiClient NS_DESIGNATED_INITIALIZER;

/// Create Rule
/// Create a new Rule
///
/// @param ruleInfo Rule object that needs to be added
/// @param userId User ID
/// 
///  code:0 message:"success"
///
/// @return ACRuleEnvelope*
-(NSURLSessionTask*) createRuleWithRuleInfo: (ACRuleCreationInfo*) ruleInfo
    userId: (NSString*) userId
    completionHandler: (void (^)(ACRuleEnvelope* output, NSError* error)) handler;


/// Delete Rule
/// Delete a Rule
///
/// @param ruleId Rule ID.
/// 
///  code:0 message:"success"
///
/// @return ACRuleEnvelope*
-(NSURLSessionTask*) deleteRuleWithRuleId: (NSString*) ruleId
    completionHandler: (void (^)(ACRuleEnvelope* output, NSError* error)) handler;


/// Get Rule
/// Get a rule using the Rule ID
///
/// @param ruleId Rule ID.
/// 
///  code:0 message:"success"
///
/// @return ACRuleEnvelope*
-(NSURLSessionTask*) getRuleWithRuleId: (NSString*) ruleId
    completionHandler: (void (^)(ACRuleEnvelope* output, NSError* error)) handler;


/// Update Rule
/// Update an existing Rule
///
/// @param ruleId Rule ID.
/// @param ruleInfo Rule object that needs to be updated
/// 
///  code:0 message:"success"
///
/// @return ACRuleEnvelope*
-(NSURLSessionTask*) updateRuleWithRuleId: (NSString*) ruleId
    ruleInfo: (ACRuleUpdateInfo*) ruleInfo
    completionHandler: (void (^)(ACRuleEnvelope* output, NSError* error)) handler;



@end
