#import <Foundation/Foundation.h>
#import "ACNotifMessagesResponse.h"
#import "ACSubscriptionEnvelope.h"
#import "ACSubscriptionInfo.h"
#import "ACSubscriptionsEnvelope.h"
#import "ACValidationCallbackInfo.h"
#import "ACApi.h"

/**
* ARTIK Cloud API
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: 2.0.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/



@interface ACSubscriptionsApi: NSObject <ACApi>

extern NSString* kACSubscriptionsApiErrorDomain;
extern NSInteger kACSubscriptionsApiMissingParamErrorCode;

-(instancetype) initWithApiClient:(ACApiClient *)apiClient NS_DESIGNATED_INITIALIZER;

/// Create Subscription
/// Create Subscription
///
/// @param subscriptionInfo Subscription details
/// 
///  code:0 message:"success"
///
/// @return ACSubscriptionEnvelope*
-(NSURLSessionTask*) createSubscriptionWithSubscriptionInfo: (ACSubscriptionInfo*) subscriptionInfo
    completionHandler: (void (^)(ACSubscriptionEnvelope* output, NSError* error)) handler;


/// Delete Subscription
/// Delete Subscription
///
/// @param subId Subscription ID.
/// 
///  code:0 message:"success"
///
/// @return ACSubscriptionEnvelope*
-(NSURLSessionTask*) deleteSubscriptionWithSubId: (NSString*) subId
    completionHandler: (void (^)(ACSubscriptionEnvelope* output, NSError* error)) handler;


/// Get All Subscriptions
/// Get All Subscriptions
///
/// @param uid User ID (optional)
/// @param offset Offset for pagination. (optional)
/// @param count Desired count of items in the result set. (optional)
/// 
///  code:0 message:"success"
///
/// @return ACSubscriptionsEnvelope*
-(NSURLSessionTask*) getAllSubscriptionsWithUid: (NSString*) uid
    offset: (NSNumber*) offset
    count: (NSNumber*) count
    completionHandler: (void (^)(ACSubscriptionsEnvelope* output, NSError* error)) handler;


/// Get Messages
/// Get Messages
///
/// @param notifId Notification ID.
/// @param offset Offset for pagination. (optional)
/// @param count Desired count of items in the result set. (optional)
/// @param order Sort order of results by ts. Either &#39;asc&#39; or &#39;desc&#39;. (optional)
/// 
///  code:0 message:"success"
///
/// @return ACNotifMessagesResponse*
-(NSURLSessionTask*) getMessagesWithNotifId: (NSString*) notifId
    offset: (NSNumber*) offset
    count: (NSNumber*) count
    order: (NSString*) order
    completionHandler: (void (^)(ACNotifMessagesResponse* output, NSError* error)) handler;


/// Get Subscription
/// Get Subscription
///
/// @param subId Subscription ID.
/// 
///  code:0 message:"success"
///
/// @return ACSubscriptionEnvelope*
-(NSURLSessionTask*) getSubscriptionWithSubId: (NSString*) subId
    completionHandler: (void (^)(ACSubscriptionEnvelope* output, NSError* error)) handler;


/// Validate Subscription
/// Validate Subscription
///
/// @param subId Subscription ID.
/// @param validationCallbackRequest Subscription validation callback request
/// 
///  code:0 message:"success"
///
/// @return ACSubscriptionEnvelope*
-(NSURLSessionTask*) validateSubscriptionWithSubId: (NSString*) subId
    validationCallbackRequest: (ACValidationCallbackInfo*) validationCallbackRequest
    completionHandler: (void (^)(ACSubscriptionEnvelope* output, NSError* error)) handler;



@end
