#import <Foundation/Foundation.h>
#import "ACTagsEnvelope.h"
#import "ACApi.h"

/**
* ARTIK Cloud API
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: 2.0.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/



@interface ACTagsApi: NSObject <ACApi>

extern NSString* kACTagsApiErrorDomain;
extern NSInteger kACTagsApiMissingParamErrorCode;

-(instancetype) initWithApiClient:(ACApiClient *)apiClient NS_DESIGNATED_INITIALIZER;

/// Get all categories
/// Get all tags marked as categories
///
/// 
///  code:0 message:"success"
///
/// @return ACTagsEnvelope*
-(NSURLSessionTask*) getTagCategoriesWithCompletionHandler: 
    (void (^)(ACTagsEnvelope* output, NSError* error)) handler;


/// Get tag suggestions
/// Get tag suggestions for applications, device types that have been most used with a group of tags.
///
/// @param entityType Entity type name. (optional)
/// @param tags Comma separated list of tags. (optional)
/// @param name Name of tags used for type ahead. (optional)
/// @param count Number of results to return. Max 10. (optional)
/// 
///  code:0 message:"success"
///
/// @return ACTagsEnvelope*
-(NSURLSessionTask*) getTagSuggestionsWithEntityType: (NSString*) entityType
    tags: (NSString*) tags
    name: (NSString*) name
    count: (NSNumber*) count
    completionHandler: (void (^)(ACTagsEnvelope* output, NSError* error)) handler;


/// Get all tags of categories
/// Get all tags related to the list of categories
///
/// @param categories Comma separated list of categories. (optional)
/// 
///  code:0 message:"success"
///
/// @return ACTagsEnvelope*
-(NSURLSessionTask*) getTagsByCategoriesWithCategories: (NSString*) categories
    completionHandler: (void (^)(ACTagsEnvelope* output, NSError* error)) handler;



@end
