#import <Foundation/Foundation.h>
#import "ACCheckTokenResponse.h"
#import "ACRefreshTokenResponse.h"
#import "ACTokenInfoSuccessResponse.h"
#import "ACTokenRequest.h"
#import "ACApi.h"

/**
* ARTIK Cloud API
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: 2.0.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/



@interface ACTokensApi: NSObject <ACApi>

extern NSString* kACTokensApiErrorDomain;
extern NSInteger kACTokensApiMissingParamErrorCode;

-(instancetype) initWithApiClient:(ACApiClient *)apiClient NS_DESIGNATED_INITIALIZER;

/// Check Token
/// (Deprecated) Check Token. See tokenInfo
///
/// @param tokenInfo Token object to be checked
/// 
///  code:0 message:"success"
///
/// @return ACCheckTokenResponse*
-(NSURLSessionTask*) checkTokenWithTokenInfo: (ACTokenRequest*) tokenInfo
    completionHandler: (void (^)(ACCheckTokenResponse* output, NSError* error)) handler;


/// Refresh Token
/// Refresh Token
///
/// @param grantType Grant Type.
/// @param refreshToken Refresh Token.
/// 
///  code:0 message:"success"
///
/// @return ACRefreshTokenResponse*
-(NSURLSessionTask*) refreshTokenWithGrantType: (NSString*) grantType
    refreshToken: (NSString*) refreshToken
    completionHandler: (void (^)(ACRefreshTokenResponse* output, NSError* error)) handler;


/// Token Info
/// Returns the Token Information
///
/// 
///  code:0 message:"success"
///
/// @return ACTokenInfoSuccessResponse*
-(NSURLSessionTask*) tokenInfoWithCompletionHandler: 
    (void (^)(ACTokenInfoSuccessResponse* output, NSError* error)) handler;



@end
