#import <Foundation/Foundation.h>
#import "ACAppProperties.h"
#import "ACDeviceSharingEnvelope.h"
#import "ACDeviceTypesEnvelope.h"
#import "ACDevicesEnvelope.h"
#import "ACPropertiesEnvelope.h"
#import "ACRulesEnvelope.h"
#import "ACUserEnvelope.h"
#import "ACApi.h"

/**
* ARTIK Cloud API
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: 2.0.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/



@interface ACUsersApi: NSObject <ACApi>

extern NSString* kACUsersApiErrorDomain;
extern NSInteger kACUsersApiMissingParamErrorCode;

-(instancetype) initWithApiClient:(ACApiClient *)apiClient NS_DESIGNATED_INITIALIZER;

/// Create User Application Properties
/// Create application properties for a user
///
/// @param userId User Id
/// @param properties Properties to be updated
/// @param aid Application ID (optional)
/// 
///  code:0 message:"success"
///
/// @return ACPropertiesEnvelope*
-(NSURLSessionTask*) createUserPropertiesWithUserId: (NSString*) userId
    properties: (ACAppProperties*) properties
    aid: (NSString*) aid
    completionHandler: (void (^)(ACPropertiesEnvelope* output, NSError* error)) handler;


/// Delete User Application Properties
/// Deletes a user's application properties
///
/// @param userId User Id
/// @param aid Application ID (optional)
/// 
///  code:0 message:"success"
///
/// @return ACPropertiesEnvelope*
-(NSURLSessionTask*) deleteUserPropertiesWithUserId: (NSString*) userId
    aid: (NSString*) aid
    completionHandler: (void (^)(ACPropertiesEnvelope* output, NSError* error)) handler;


/// Get Current User Profile
/// Get's the current user's profile
///
/// 
///  code:0 message:"success"
///
/// @return ACUserEnvelope*
-(NSURLSessionTask*) getSelfWithCompletionHandler: 
    (void (^)(ACUserEnvelope* output, NSError* error)) handler;


/// Get User Device Types
/// Retrieve User's Device Types
///
/// @param userId User ID.
/// @param offset Offset for pagination. (optional)
/// @param count Desired count of items in the result set (optional)
/// @param includeShared Optional. Boolean (true/false) - If false, only return the user&#39;s device types. If true, also return device types shared by other users. (optional)
/// 
///  code:0 message:"success"
///
/// @return ACDeviceTypesEnvelope*
-(NSURLSessionTask*) getUserDeviceTypesWithUserId: (NSString*) userId
    offset: (NSNumber*) offset
    count: (NSNumber*) count
    includeShared: (NSNumber*) includeShared
    completionHandler: (void (^)(ACDeviceTypesEnvelope* output, NSError* error)) handler;


/// Get User Devices
/// Retrieve User's Devices
///
/// @param userId User ID
/// @param offset Offset for pagination. (optional)
/// @param count Desired count of items in the result set (optional)
/// @param includeProperties Optional. Boolean (true/false) - If false, only return the user&#39;s device types. If true, also return device types shared by other users. (optional)
/// @param owner Return owned and/or shared devices. Default to ALL. (optional)
/// @param includeShareInfo Include share info (optional)
/// @param dtid Return only devices of this device type. If empty, assumes all device types allowed by the authorization. (optional)
/// 
///  code:0 message:"success"
///
/// @return ACDevicesEnvelope*
-(NSURLSessionTask*) getUserDevicesWithUserId: (NSString*) userId
    offset: (NSNumber*) offset
    count: (NSNumber*) count
    includeProperties: (NSNumber*) includeProperties
    owner: (NSString*) owner
    includeShareInfo: (NSNumber*) includeShareInfo
    dtid: (NSString*) dtid
    completionHandler: (void (^)(ACDevicesEnvelope* output, NSError* error)) handler;


/// Get User application properties
/// Get application properties of a user
///
/// @param userId User Id
/// @param aid Application ID (optional)
/// 
///  code:0 message:"success"
///
/// @return ACPropertiesEnvelope*
-(NSURLSessionTask*) getUserPropertiesWithUserId: (NSString*) userId
    aid: (NSString*) aid
    completionHandler: (void (^)(ACPropertiesEnvelope* output, NSError* error)) handler;


/// Get User Rules
/// Retrieve User's Rules
///
/// @param userId User ID.
/// @param excludeDisabled Exclude disabled rules in the result. (optional)
/// @param count Desired count of items in the result set. (optional)
/// @param offset Offset for pagination. (optional)
/// @param owner Rule owner (optional)
/// 
///  code:0 message:"success"
///
/// @return ACRulesEnvelope*
-(NSURLSessionTask*) getUserRulesWithUserId: (NSString*) userId
    excludeDisabled: (NSNumber*) excludeDisabled
    count: (NSNumber*) count
    offset: (NSNumber*) offset
    owner: (NSString*) owner
    completionHandler: (void (^)(ACRulesEnvelope* output, NSError* error)) handler;


/// Get User shares
/// Get User shares
///
/// @param userId User ID.
/// @param filter filter
/// @param count Desired count of items in the result set. (optional)
/// @param offset Offset for pagination. (optional)
/// 
///  code:0 message:"success"
///
/// @return ACDeviceSharingEnvelope*
-(NSURLSessionTask*) listAllSharesForUserWithUserId: (NSString*) userId
    filter: (NSString*) filter
    count: (NSNumber*) count
    offset: (NSNumber*) offset
    completionHandler: (void (^)(ACDeviceSharingEnvelope* output, NSError* error)) handler;


/// Update User Application Properties
/// Updates application properties of a user
///
/// @param userId User Id
/// @param properties Properties to be updated
/// @param aid Application ID (optional)
/// 
///  code:0 message:"success"
///
/// @return ACPropertiesEnvelope*
-(NSURLSessionTask*) updateUserPropertiesWithUserId: (NSString*) userId
    properties: (ACAppProperties*) properties
    aid: (NSString*) aid
    completionHandler: (void (^)(ACPropertiesEnvelope* output, NSError* error)) handler;



@end
